nginx:
    build: .
    ports:
        - "80:80"
        - "9200:9200"
    links:
        - elasticsearch
        - kibana

elasticsearch:
    image: elasticsearch
    volumes:
        - ./esdata:/usr/share/elasticsearch/data

kibana:
    image: kibana
    links:
        - elasticsearch

